spring:
  application:
    name: api
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost/Merkand # localhost:5433/Merkand
    username: postgres #root
    password: root #root1234@
    driver-class-name: org.postgresql.Driver
token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
    expiration-ms: 3600000 # 1 hour

